### ISSUE TITLE
Missing dependency causing crash on Win11x64

### ISSUE THREAD

**Issue by paulrobello** [pommee/Pocker#6]
Running under gitbash on windows 11 x64 
```
$ pipx install git+https://github.com/pommee/Pocker
  installed package pocker 1.11.3, installed using Python 3.12.4
  These apps are now globally available
    - pocker.exe
done! ✨ 🌟 ✨
paulr@PAR-BEAST-LTP ~
$ pocker
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\users\paulr\.local\bin\pocker.exe\__main__.py", line 4, in <module>
  File "C:\Users\paulr\pipx\venvs\pocker\Lib\site-packages\application\main.py", line 36, in <module>
    from application.widget.content import ContentWindow
  File "C:\Users\paulr\pipx\venvs\pocker\Lib\site-packages\application\widget\content.py", line 18, in <module>
    from application.widget.shell import ShellPane
  File "C:\Users\paulr\pipx\venvs\pocker\Lib\site-packages\application\widget\shell.py", line 2, in <module>
    import pty
  File "C:\Python312\Lib\pty.py", line 12, in <module>
    import tty
  File "C:\Python312\Lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```

**Comment by pommee** [comment]
Thanks for reporting.  

No testing has been done on Windows, but will have a look.

**Comment by pommee** [comment]
Update:

termios is a package (built into Python) used in Unix systems, i.e not Windows.  
My intention was not to make Pocker supported on Windows, but if there is interest and/or priorities change then I will certainly look into it further.  

Also, feel free to create a PR if you have a look at it and find any success. Might ease the process in the future.  

I will leave this issue open as more people might find this being wanted.

**Comment by pommee** [comment]
Linked https://github.com/pommee/Pocker/pull/7

**Comment by pommee** [comment]
Windows support fixed.  

Closing.
